services:
  
  cumulus-etl:
    build: .
    environment:
      - URL_CTAKES_REST=http://ctakes-covid:8080/ctakes-web-rest/service/analyze
    # TODO: This platform requirement is due to the dotnet runtime flag.
    # We could investigate dynamically passing the system architecture?
    platform: linux/x86_64
    networks:
      - cumulus-etl
    profiles:
      - etl

    
  ctakes-covid:
    image: smartonfhir/ctakes-covid
    environment:
      - ctakes_umlsuser=umls_api_key 
      - ctakes_umlspw=$UMLS_API_KEY
    networks:
      - cumulus-etl
    # If you need to expose the ctakes server for testing, uncomment this port mapping
    # ports:
    #   - 8080:8080
    profiles:
      - etl-support
      - test

  # this image is intended specifically for development work
  cumulus-etl-test:
    extends:
      service: cumulus-etl
    volumes: 
      - ./:/cumulus-etl/
    profiles:
      - test
    entrypoint: 
      - /bin/sh 
      - -c
    command: "cumulus-etl /cumulus-etl/tests/data/simple/ndjson-input /cumulus-etl/example-output /cumulus-etl/example-phi-build --output-format=ndjson"


networks:
  cumulus-etl:
    name: cumulus-etl
