services:

  cumulus-etl-base:
    build: 
      context: .
      target: cumulus-etl
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - URL_CTAKES_REST=http://ctakes-covid:8080/ctakes-web-rest/service/analyze
      - URL_CNLP_NEGATION=http://cnlp-transformers:8000/negation/process
    volumes:
      - $HOME/.aws/:/root/.aws/:ro
    networks:
      - cumulus-etl
    profiles:
      - base

  cumulus-etl:
    extends: cumulus-etl-base
    profiles:
      - etl

  cumulus-etl-gpu:
    extends: cumulus-etl-base
    environment:
      - URL_CNLP_NEGATION=http://cnlp-transformers-gpu:8000/negation/process
    profiles:
      - etl-gpu

  ctakes-covid-base:
    image: smartonfhir/ctakes-covid:1
    environment:
      - ctakes_umlsuser=umls_api_key 
      - ctakes_umlspw=$UMLS_API_KEY
    networks:
      - cumulus-etl
    profiles:
      - base

  ctakes-covid:
    extends: ctakes-covid-base
    profiles:
      - etl-support
      - etl-support-gpu

  cnlp-transformers:
    image: smartonfhir/cnlp-transformers:negation-0.4-cpu
    profiles:
      - etl-support
    networks:
      - cumulus-etl

  cnlp-transformers-gpu:
    image: smartonfhir/cnlp-transformers:negation-0.4-gpu
    profiles:
      - etl-support-gpu
    networks:
      - cumulus-etl
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  # these images are intended specifically for development work
  cumulus-etl-test:
    extends:
      service: cumulus-etl-base
    build: 
      context: .
      target: cumulus-etl-test
    environment:
      - URL_CTAKES_REST=http://ctakes-covid-test:8080/ctakes-web-rest/service/analyze
      - URL_CNLP_NEGATION=http://cnlp-transformers-test:8000/negation/process
    volumes: 
      - ./:/cumulus-etl/
    working_dir: /cumulus-etl
    command: 
      - /cumulus-etl/tests/data/simple/ndjson-input 
      - /cumulus-etl/example-output 
      - /cumulus-etl/example-phi-build 
      - --output-format=ndjson
    profiles:
      - test

  cumulus-etl-test-gpu:
    extends:
      service: cumulus-etl-base
    build: 
      context: .
      target: cumulus-etl-test
    environment:
      - URL_CTAKES_REST=http://ctakes-covid-test:8080/ctakes-web-rest/service/analyze
      - URL_CNLP_NEGATION=http://cnlp-transformers-test-gpu:8000/negation/process
    volumes: 
      - ./:/cumulus-etl/
    working_dir: /cumulus-etl
    command: 
      - /cumulus-etl/tests/data/simple/ndjson-input 
      - /cumulus-etl/example-output 
      - /cumulus-etl/example-phi-build 
      - --output-format=ndjson
    profiles:
      - test-gpu


  ctakes-covid-test:
    extends:
      service: ctakes-covid-base
    profiles:
      - test
      - test-gpu
    ports:
      - 8080:8080

  cnlp-transformers-test:
    image: smartonfhir/cnlp-transformers:negation-latest-cpu
    #build: 
    #  context: ../cnlp_transformers/docker
    #  dockerfile: Dockerfile.cpu
    ports:
      - 8000:8000
    profiles:
      - test
    networks:
      - cumulus-etl

  cnlp-transformers-test-gpu:
    image: smartonfhir/cnlp-transformers:negation-latest-gpu
    #build: 
    #  context: ../cnlp_transformers/docker
    #  dockerfile: Dockerfile.gpu
    ports:
      - 8000:8000
    profiles:
      - test-gpu
    networks:
      - cumulus-etl
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

networks:
  cumulus-etl:
    name: cumulus-etl
