services:
  
  cumulus-etl:
    build: 
      context: .
      target: cumulus-etl
    environment:
      - URL_CTAKES_REST=http://ctakes-covid:8080/ctakes-web-rest/service/analyze
    # TODO: This platform requirement is due to the dotnet runtime flag.
    # We could investigate dynamically passing the system architecture?
    platform: linux/x86_64
    networks:
      - cumulus-etl
    profiles:
      - etl

    
  ctakes-covid:
    image: smartonfhir/ctakes-covid:1
    environment:
      - ctakes_umlsuser=umls_api_key 
      - ctakes_umlspw=$UMLS_API_KEY
    networks:
      - cumulus-etl
    # If you need to expose the ctakes server for testing, uncomment this port mapping
    ports:
      - 8080:8080
    profiles:
      - etl-support
      - test

  cnlp-transformers:
    build: smartonfhir/cnlp-transformer:dev
    #platform: linux/amd64
    ports:
      - 8000:8000
    profiles:
      - etl-support
      - test
    networks:
      - cumulus-etl

  # this image is intended specifically for development work
  cumulus-etl-test:
    extends:
      service: cumulus-etl
    build: 
      context: .
      target: cumulus-etl-test
    volumes: 
      - ./:/cumulus-etl/
    working_dir: /cumulus-etl
    profiles:
      - test
    command: 
      - /cumulus-etl/tests/data/simple/ndjson-input 
      - /cumulus-etl/example-output 
      - /cumulus-etl/example-phi-build 
      - --output-format=ndjson


networks:
  cumulus-etl:
    name: cumulus-etl
