NLP_EXTENSION ::= 'resourceType' Observation 'id' ID 'status' Provenance 'code' 'coding' Coding+ 'extension' TextPosition 'subject' Subject 'encounter' Encounter 'modifierExtension' Algorithm Polarity

Observation::= ('Observation' | 'https://www.hl7.org/fhir/observation.html')

Provenance::= ('unknown' | 'https://build.fhir.org/provenance.html')

Coding::= (History COVID19 TUI) | ('https://hl7.org/fhir/datatypes-definitions.html#Coding')

History::= 'system' 'http://snomed.info/sct' 'code' '392521001' 'display' 'History'

COVID19::= 'system' 'urn:oid:2.16.840.1.113883.6.86' 'code' 'C0262926' 'display' '2019 Novel Coronavirus COVID 19 Codeset'

TUI::= 'system' 'https://www.ncbi.nlm.nih.gov/books/NBK9679' 'code' 'T033' 'display' 'UMLS Semantic Type Unique Identifier'

TextPosition::= 'url' 'http://fhir-registry.smarthealthit.org/StructureDefinition/nlp-text-position' 'extension' ('url' 'begin' 'valueInteger' INT 'url' 'end' INT)

Algorithm::= 'url' 'http://fhir-registry.smarthealthit.org/StructureDefinition/nlp-algorithm' 'extension' 'url' 'dateofauthorship' 'valueDate' ('2021-06-23'|'https://www.hl7.org/fhir/datatypes.html#date')

Polarity::= 'url' 'http://fhir-registry.smarthealthit.org/StructureDefinition/nlp-polarity' 'valueInteger' ('0'|'1')

Subject::= ('reference' UUID) | 'https://www.hl7.org/fhir/observation-definitions.html#Observation.subject'

Encounter::= ('reference' UUID) | 'https://www.hl7.org/fhir/observation-definitions.html#Observation.encounter' 

ID::= 'https://www.hl7.org/fhir/resource-definitions.html#Resource.id'

UUID::= 'https://hl7.org/fhir/datatypes.html#uuid'

INT::= 'https://build.fhir.org/datatypes.html#unsignedInt'










