FHIR::=

    (Population 'http://hl7.org/fhir/population-definitions.html')|
    (Patient	'http://hl7.org/fhir/patient.html')|
    (Gender     'http://hl7.org/fhir/valueset-administrative-gender.html')|
    (Race       'http://hl7.org/fhir/us/core/StructureDefinition/us-core-race')|
    (Ethnicity  'http://hl7.org/fhir/us/core/ValueSet/detailed-ethnicity')|

    (Encounter			'http://hl7.org/fhir/encounter.html')|
    (EncounterStatus	'http://hl7.org/fhir/encounter-status')|
    (Hospitalization    'http://hl7.org/fhir/encounter-definitions.html#Encounter.hospitalization'|
    (EncounterCode		'http://hl7.org/fhir/v3/ActEncounterCode/vs.html')|
    (AdmitSource		'http://hl7.org/fhir/valueset-encounter-admit-source.html')|
    (DischargeDisposition	'http://hl7.org/fhir/valueset-encounter-discharge-disposition.html')|
    (ServiceType 		'http://hl7.org/fhir/ValueSet/service-type')|
    
    (Condition 		'http://hl7.org/fhir/condition-definitions.html')|
    (ConditionCode	'http://hl7.org/fhir/valueset-condition-code.html')|
    (ConditionCategory	'http://hl7.org/fhir/valueset-condition-category.html')|
    (Severity		'http://hl7.org/fhir/valueset-condition-severity.html')|
    
    (Procedure		'http://hl7.org/fhir/procedure.html')|
    (ProcedureCode	'http://hl7.org/fhir/valueset-procedure-code.html')|
    (ProcedureCategory 'http://hl7.org/fhir/valueset-procedure-category.html')|

    (ObservationCode		'http://hl7.org/fhir/ValueSet/observation-codes')|
    (ObservationCategory	'http://hl7.org/fhir/valueset-observation-category.html')|
    (ObservationInterpretation 	'http://hl7.org/fhir/valueset-observation-interpretation.html')|
    (VitalSign			'http://hl7.org/fhir/observation-vitalsigns.html')|

    (NDFRT			'http://hl7.org/fhir/ndfrt')|
    (Medication       		'http://hl7.org/fhir/medication.html')|
    (MedicationCategory 	'http://hl7.org/fhir/valueset-medication-statement-category.html')|

    (Immunization      'http://hl7.org/fhir/immunization.html')|
    (ImmunizationRoute 'http://hl7.org/fhir/valueset-immunization-route.html')|
    (VaccineCode       'http://hl7.org/fhir/valueset-vaccine-code.html')|

    (ClinicalTerm     'http://snomed.info/sct')|
    (BodySite 	      'http://hl7.org/fhir/valueset-body-site.html')|
    (Finding          'http://hl7.org/fhir/ValueSet/clinical-findings')|

    (Coding 	      'http://hl7.org/fhir/datatypes.html#Coding')|
    (Range 	      'http://hl7.org/fhir/datatypes.html#Range')|
    (Period 	      'http://hl7.org/fhir/datatypes.html#Period')|
    (Quantity	      'http://hl7.org/fhir/datatypes.html#Quantity')|
    (PostalCode	      'http://hl7.org/fhir/datatypes-definitions.html#Address.postalCode')|    
    (Duration	      'http://hl7.org/fhir/datatypes.html#Duration')|
    (DurationUnits    'http://hl7.org/fhir/valueset-all-time-units.html')|

    (code 	      'http://hl7.org/fhir/datatypes.html#code')|
    (url	      'http://hl7.org/fhir/datatypes.html#url')|
    (date	      'http://hl7.org/fhir/datatypes.html#date')|
    (dateTime	      'http://hl7.org/fhir/datatypes.html#dateTime')|
    (integer	      'http://hl7.org/fhir/datatypes.html#integer')|
    (url	      'http://hl7.org/fhir/datatypes.html#url')|
    (boolean	      'http://hl7.org/fhir/datatypes.html#boolean')|
    (total	      'http://hl7.org/fhir/search.html#total')|


Criteria::= Population+ Rollup
Population::= Patient* ClinicalTerm* Encounter* Condition* Procedure* Medication* (Observation|VitalSign)*
Rollup::= ('age'|'gender'|'race'|'zipcode'|'year'|'month'|'day')

Population::= Gender* Age? Zipcode*
Age::= Range|integer*
Zipcode::= integer

ClinicalTerm::= Coding

Encounter::= Period? Duration? ServiceType* EncounterStatus* EncounterCode* Hospitalization?

Hospitalization::= boolean | (AdmitSource* DischargeDisposition*)

Condition::= Coding ConditionCategory? BodySite* Severity*
ConditionCategory::= 'problem-list-item'|'encounter-diagnosis'
Severity::= Coding | ('Severe'|'Moderate'|'Mild')

Procedure::= Coding ProcedureCategory* BodySite*
ProcedureCategory::= Coding | ('psych'|'counselling'|'education'|'surgical'|'diagnostic'|'chiro'|'social')

Observation::= Coding ObservationCategory* ObservationInterpretation* Result*
ObservationCategory::= ('social-history'|'vital-signs'|'imaging'|'laboratory'|'procedure'|'survey'|'exam'|'therapy'|'activity')
ObservationInterpretation::= Coding | ('genetic'|'change'|'exception'|'normality'|'microbial'|'detection'|'susceptibility')
ObservationValue::= Coding Quantity Range Period integer boolean

VitalSign::= Observation

Medication::= (Coding|NDFRT) Period? MedicationCategory* ConditionCode*
MedicationCategory::= Coding| ('inpatient'|'outpatient'|'community'|'patientspecified')

Immunization::= VaccineCode ImmunizationRoute? Period

Coding::= (url code display?)

Range::= ('low' (integer|Quantity)? 'high' (integer|Quantity)?)
Duration::= DurationUnits | (('hours'|'days'|'months'|'years'|'weeks') integer)
Period::= 'start' dateTime 'end' dateTime
dateTime::= 'YYYY'| 'YYYY-MM' |'YYYY-MM-DD'


