FHIR::= (Population 'http://hl7.org/fhir/population-definitions.html')|
(Patient 'http://hl7.org/fhir/patient.html')|
(Gender 'http://hl7.org/fhir/ValueSet/administrative-gender')|
(Race 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-race')|
(Ethnicity 'http://hl7.org/fhir/us/core/ValueSet/detailed-ethnicity')|
(ObservationCode 'http://hl7.org/fhir/ValueSet/observation-codes')|
(ObservationCategory 'http://hl7.org/fhir/ValueSet/observation-category')|
(ObservationValue 'http://hl7.org/fhir/observation-definitions.html#Observation.value_x_')|
(ObservationInterpretation 'http://hl7.org/fhir/ValueSet/observation-interpretation')|
(VitalSign 'http://hl7.org/fhir/observation-vitalsigns.html')|
(Encounter 'http://hl7.org/fhir/encounter.html')|
(EncounterPeriod 'http://hl7.org/fhir/encounter-definitions.html#Encounter.period')|
(EncounterStatus 'http://hl7.org/fhir/encounter-status')|
(EncounterCode 'http://hl7.org/fhir/v3/ActEncounterCode/vs.html')|
(Hospitalization 'http://hl7.org/fhir/encounter-definitions.html#Encounter.hospitalization')|
(AdmitSource 'http://hl7.org/fhir/ValueSet/encounter-admit-source')|
(DischargeDisposition 'http://hl7.org/fhir/ValueSet/encounter-discharge-disposition')|
(ServiceType 'http://hl7.org/fhir/ValueSet/service-type')|
(ClinicalTerm 'http://snomed.info/sct')|
(BodySite 'http://hl7.org/fhir/ValueSet/body-site')|
(Finding 'http://hl7.org/fhir/ValueSet/clinical-findings')|
(Condition 'http://hl7.org/fhir/condition-definitions.html')|
(ConditionCode 'http://hl7.org/fhir/ValueSet/condition-code')|
(ConditionCategory 'http://hl7.org/fhir/ValueSet/condition-category')|
(Severity 'http://hl7.org/fhir/ValueSet/condition-severity')|
(Procedure 'http://hl7.org/fhir/procedure.html')|
(ProcedureCode 'http://hl7.org/fhir/ValueSet/procedure-code')|
(ProcedureCategory 'http://hl7.org/fhir/ValueSet/procedure-category')|
(Medication 'http://www.nlm.nih.gov/research/umls/rxnorm')|
(MedicationForm 'http://hl7.org/fhir/ValueSet/medication-form-codes')|
(MedicationCategory 'http://hl7.org/fhir/ValueSet/medication-statement-category')|
(VaccineCode 'http://hl7.org/fhir/ValueSet/vaccine-code')|
(Immunization 'http://hl7.org/fhir/immunization.html')|
(Coding 'http://hl7.org/fhir/datatypes.html#Coding')|
(Range 'https://hl7.org/fhir/datatypes.html#Range')|
(Period 'http://hl7.org/fhir/datatypes.html#Period')|
(Duration 'http://hl7.org/fhir/datatypes.html#Duration')|
(DurationUnits 'http://hl7.org/fhir/valueset-duration-units.html')|
(Units 'http://hl7.org/fhir/ValueSet/ucum-units')|
(Date 'https://www.hl7.org/fhir/datatypes.html#date')|
(PostalCode 'http://hl7.org/fhir/datatypes-definitions.html#Address.postalCode')|
(Criteria 'http://hl7.org/fhir/search.html#count')|
(Int 'http://hl7.org/fhir/datatypes.html#positiveInt')|
(COVID19_Symptoms 'http://build.fhir.org/ig/HL7/fhir-COVID19Library-ig/ValueSet-covid19-signs-1nd-symptoms-value-set.html')|
(UMLS 'http://www.nlm.nih.gov/research/umls/')|
(LOINC 'http://loinc.org')|
(ICD9 'http://hl7.org/fhir/sid/icd-9-cm')|
(ICD10 'http://hl7.org/fhir/sid/icd-10-cm')|
(CPT 'http://www.ama-assn.org/go/cpt')
Population::= Patient* ClinicalTerm* Encounter* Condition* ObservationInterpretation*
Patient::= Gender* Race* Age*
Gender::= (code 'male' display 'M')|
(code 'female' display 'F')|
(code 'transgender-female' display 'T')|
(code 'transgender-male' display 'T')|
(code 'non-binary' display 'U')|
(code 'non-disclose' display 'U')|
(code 'other' display 'U')|
(code 'unknown' display 'U')
Race::= (code '1002-5' display 'American Indian or Alaska Native')|
(code '2028-9' display 'Asian')|
(code '2054-5' display 'Black or African American')|
(code '2076-8' display 'Native Hawaiian or Other Pacific Islander')|
(code '2106-3' display 'White')
Age::= Range
Encounter::= Period DurationUnits
Range::= low? high?
Period::= start end
DurationUnits::= (code 'ms' display 'milliseconds')|
(code 's' display 'seconds')|
(code 'min' display 'minutes')|
(code 'h' display 'hours')|
(code 'd' display 'days')|
(code 'wk' display 'weeks')|
(code 'mo' display 'months')|
(code 'a' display 'years')
Coding::= code display system userSelected?
