[shared]
system-prompt = """
You are a clinical chart reviewer for an IBD (inflammatory bowel disease) outcomes study.
Your task is to extract patient-specific information from an unstructured clinical 
document and map it into a predefined Pydantic schema.

Core Rules:
1. Base all assertions ONLY on patient-specific information in the clinical document.
   - Never negate or exclude information just because it is not mentioned.
   - Never conflate family history or population-level risk with patient findings.
   - Do not count past medical history, prior episodes, or family history.
   - Spans provided should ALWAYS be verbatim.
2. Do not invent or infer facts beyond what is documented.
3. Citing spans should be exact text from the clinical document, not paraphrased or shorthand.
4. Answer patient outcomes with strongest available documented evidence. E.g.
    BIOPSY_PROVEN > CONFIRMED > SUSPECTED > NONE_OF_THE_ABOVE.
5. Always produce structured JSON that conforms to the Pydantic schema provided below.

Pydantic Schema:
%JSON-SCHEMA%
"""

user-prompt = """
Evaluate the following clinical document for IBD variables and outcomes.
Here is the clinical document for you to analyze:

%CLINICAL-NOTE%
"""

models = [
    "claude-sonnet45",
    "gpt51",
    "gpt-oss-120b",
]

use-mlflow = true

mlflow-experiment-name = "ibd_etl_infra_test"

[[task]]
name = "diagnosis"
response-schema = "ibd-diagnosis-annotation.json"
# Version History:
# ** 4 (2026-05): Adds IBD Activity and Severity; 
#                 Minor changes to has_mention in SpanAugmentedMention
# ** 3 (2026-04): Various changes to base-classes (e.g. SpanAugmentedMention)
# ** 2 (2026-04): Fixes uses of irritable bowel disease (IBD) to inflammatory bowel disease (IBD)
# ** 1 (2026-03): Initial version
version = 4

[[task]]
name = "genetic_findings"
response-schema = "ibd-genetic-findings-annotation.json"
# Version History:
# ** 4 (2026-05): Minor changes to has_mention in SpanAugmentedMention base class
# ** 3 (2026-04): Various changes to base-classes (e.g. SpanAugmentedMention)
# ** 2 (2026-04): Fixes uses of irritable bowel disease (IBD) to inflammatory bowel disease (IBD)
# ** 1 (2026-03): Initial version
version = 4

[[task]]
name = "paris_classification"
response-schema = "ibd-paris-classification-annotation.json"
# Version History:
# ** 4 (2026-05): Minor changes to has_mention in SpanAugmentedMention base class
# ** 3 (2026-04): Various changes to base-classes (e.g. SpanAugmentedMention)
# ** 2 (2026-04): Fixes uses of irritable bowel disease (IBD) to inflammatory bowel disease (IBD)
# ** 1 (2026-03): Initial version
version = 4

[[task]]
name = "treatment"
response-schema = "ibd-treatment-annotation.json"
# Version History:
# ** 5 (2026-05): Minor changes to has_mention in SpanAugmentedMention base class
# ** 4 (2026-04): Various changes to base-classes (e.g. SpanAugmentedMention)
# ** 3 (2026-04): Fixes uses of irritable bowel disease (IBD) to inflammatory bowel disease (IBD)
# ** 2 (2026-03-23): New medication model
# ** 1 (2026-03): Initial version
version = 5

[[task]]
name = "surgery"
response-schema = "ibd-surgery-annotation.json"
# Version History:
# ** 4 (2026-05): Minor changes to has_mention in SpanAugmentedMention base class
# ** 3 (2026-04): Various changes to base-classes (e.g. SpanAugmentedMention)
# ** 2 (2026-04): Fixes uses of irritable bowel disease (IBD) to inflammatory bowel disease (IBD)
# ** 1 (2026-03): Initial version
version = 4

[[task]]
name = "eim"
response-schema = "ibd-eim-annotation.json"
# Version History:
# ** 2 (2026-05): Minor changes to has_mention in SpanAugmentedMention base class
# ** 1 (2026-04): Initial version
version = 2

[[task]]
name = "endoscopy"
response-schema = "ibd-endoscopy-annotation.json"
# Version History:
# ** 2 (2026-05): Minor changes to has_mention in SpanAugmentedMention base class
# ** 1 (2026-04): Initial version
version = 2

[[task]]
name = "mayo_score"
response-schema = "ibd-mayo-score-annotation.json"
# Version History:
# ** 2 (2026-05): Minor changes to has_mention in SpanAugmentedMention base class
# ** 1 (2026-04): Initial version
version = 2

[[task]]
name = "pcdai"
response-schema = "ibd-pcdai-annotation.json"
# Version History:
# ** 2 (2026-05): Minor changes to has_mention in SpanAugmentedMention base class
# ** 1 (2026-04): Initial version
version = 2

[[task]]
name = "pucai"
response-schema = "ibd-pucai-annotation.json"
# Version History:
# ** 2 (2026-05): Minor changes to has_mention in SpanAugmentedMention base class
# ** 1 (2026-04): Initial version
version = 2

[[task]]
name = "sescd"
response-schema = "ibd-sescd-annotation.json"
# Version History:
# ** 2 (2026-05): Minor changes to has_mention in SpanAugmentedMention base class
# ** 1 (2026-04): Initial version
version = 2

[[task]]
name = "stooling"
response-schema = "ibd-stooling-annotation.json"
# Version History:
# ** 2 (2026-05): Minor changes to has_mention in SpanAugmentedMention base class
# ** 1 (2026-04): Initial version
version = 2

[[task]]
name = "uceis"
response-schema = "ibd-uceis-annotation.json"
# Version History:
# ** 2 (2026-05): Minor changes to has_mention in SpanAugmentedMention base class
# ** 1 (2026-04): Initial version
version = 2

[[task]]
name = "document_type"
response-schema = "ibd-document-type-annotation.json"
# Version History:
# ** 2 (2026-05): Minor changes to has_mention in SpanAugmentedMention base class
# ** 1 (2026-04): Initial version
version = 2

[[task]]
name = "topic_relevance"
response-schema = "ibd-topic-relevance-annotation.json"
# Version History:
# ** 2 (2026-05): Minor changes to has_mention in SpanAugmentedMention base class
# ** 1 (2026-04): Initial version
version = 2
