name: PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # this permission is required for PyPI "trusted publishing"

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Set version from tag
      run: |
        ETL_VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//')
        sed -i "s/0\.0\.0/$ETL_VERSION/" cumulus_etl/__init__.py

    - name: Build
      run: python -m build

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
